function prettyPlotLoop(figure_handle,fontSize,showYTicks)
if  nargin < 3
    showYTicks = 'No';
end
if nargin < 2
    fontSize = 14;
end
allobj = findobj(figure_handle);
dbstop if error
for i = 1:length(allobj)
    switch class(allobj(i))
        case 'matlab.graphics.illustration.Legend'
            set(allobj(i), 'FontSize', fontSize,...
                'Location','Best');
        case 'matlab.graphics.chart.primitive.Line'
            for j = 1:length(allobj(i))
                if isequal(allobj(i).Marker,'o') | isequal(allobj(i).Marker,'^' | isequal(allobj(i).Marker,'.'))
                    set(allobj(i), ...
                        'LineWidth'       , 3           , ...            
                        'MarkerSize'      , 15            );
                else
                    set(allobj(i), 'LineWidth', 2);
                end
            end
        case 'matlab.graphics.axis.Axes'
            set(allobj(i), ...
                'FontSize'    , fontSize         , ...
                'FontName'    , 'Helvetica',...
                'Box'         , 'off'      , ...
                'TickDir'     , 'out'      , ...
                'TickLength'  , [.02 .02]  , ...
                'XMinorTick'  , 'on'       , ...
                'YMinorTick'  , 'on'       , ...
                'YGrid'       , 'on'       , ...
                'XColor'      , [.3 .3 .3] , ...
                'YColor'      , [.3 .3 .3] , ...
                'LineWidth'   , 1         );
            switch showYTicks
                case 'No'
                    set(allobj(i), 'YTickLabel'  , []);
                otherwise
            end
            
        case 'matlab.graphics.primitive.Text'
            if isequal(allobj(i).Interpreter,'latex')
                set( allobj(i)  ,...
                    'FontName'    , 'Helvetica',...
                    'FontSize'    , 20         );
            else
                set( allobj(i)  ,...
                    'FontName'    , 'Helvetica',...
                    'FontSize'    , fontSize         );
            end
        case 'matlab.graphics.chart.primitive.ErrorBar'
            set(allobj(i)                       , ...
                'LineWidth'       , 1           , ...
                'MarkerSize'      , 6           , ...
                'MarkerEdgeColor' , [.2 .2 .2]  , ...
                'MarkerFaceColor' , allobj(i).Color  );
        otherwise
%             disp([inputname(i) ' was not changed'])
    end
end

